/* Lux Database service worker (generated by build.py from sw.template.js — edit the template, not sw.js).
   - App shell (pages, icons, scanner JS, vendor libs) is cached so the installed app opens instantly / offline.
   - Pages and DATA are NETWORK-FIRST with the HTTP cache bypassed, so they are never stale; the cache is only an offline fallback.
     Data = data.json, status.json, selman.json, auctions/*, inventory.csv, teslas.csv.
   - Anything with ?v= (the "Reload site" button) goes straight to the network.
   - Other origins (Cloudflare Worker /vin-ocr and /auction, fonts, listing photos) and non-GET requests are not touched. */
const VER = 'lux-2026-10-10T17:07:50';
const SHELL = ['./', 'auction.html', 'manifest.webmanifest', 'icons/icon-192.png', 'icons/apple-touch-icon.png', 'icons/lux-logo-h64.png', 'icons/favicon-32.png'];
const DATA = /(?:\/|^)(?:data\.json|status\.json|selman\.json|inventory\.csv|teslas\.csv)$|\/auctions\//;
const STATIC = /\/(?:vendor|icons)\/|\.(?:js|png|jpg|svg|ico|woff2?|webmanifest)$/;

self.addEventListener('install', e => {
  e.waitUntil(caches.open(VER).then(c => Promise.all(SHELL.map(u => fetch(u, {cache: 'reload'}).then(r => r.ok && c.put(u, r)).catch(() => {})))).then(() => self.skipWaiting()));
});
self.addEventListener('activate', e => {
  e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k.startsWith('lux-') && k !== VER).map(k => caches.delete(k)))).then(() => self.clients.claim()));
});
const clean = r => r.redirected ? r.blob().then(b => new Response(b, {status: r.status, statusText: r.statusText, headers: r.headers})) : r;
async function networkFirst(req, key, store) {
  try {
    let r = await fetch(req.url, {cache: 'no-store', credentials: 'same-origin'});
    r = await clean(r);
    if (store && r.ok) { const c = await caches.open(VER); c.put(key, r.clone()); }
    return r;
  } catch (err) {
    const hit = await caches.match(key, {ignoreSearch: true});
    if (hit) return hit;
    if (req.mode === 'navigate') { const home = await caches.match('./'); if (home) return home; }
    throw err;
  }
}
async function staleWhileRevalidate(e, req) {
  const c = await caches.open(VER), hit = await c.match(req);
  const net = fetch(req).then(r => { if (r.ok && r.type === 'basic') c.put(req, r.clone()); return r; });
  if (hit) { e.waitUntil(net.catch(() => {})); return hit; }
  return net;
}
self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  const path = url.pathname, isPage = req.mode === 'navigate' || /\/$|\.html$/.test(path);
  if (isPage) {               // network-first; ?v= (Reload site) also lands here and refreshes the offline copy
    e.respondWith(networkFirst(req, url.origin + path, true)); return;
  }
  if (DATA.test(path)) { e.respondWith(networkFirst(req, url.origin + path, true)); return; }
  if (url.searchParams.has('v') && !/\.js$/.test(path)) { e.respondWith(fetch(req.url, {cache: 'no-store'})); return; }
  if (STATIC.test(path)) { e.respondWith(staleWhileRevalidate(e, req)); return; }
  // everything else (CARFAX PDFs, CSV downloads…): plain network, no caching
});

// ---- Web Push: "Auction report ready" (sent by the Worker /notify when auction.py finishes a VIN) ----
self.addEventListener('push', e => {
  let d = {}; try { d = e.data ? e.data.json() : {}; } catch (err) { d = { title: 'Lux', body: e.data ? e.data.text() : '' }; }
  const url = d.url || ('auction.html' + (d.vin ? '#vin=' + d.vin : ''));
  e.waitUntil((async () => {
    // tell open auction pages so they refresh at once (they also poll every 15 s)
    const cs = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
    cs.forEach(c => c.postMessage({ type: 'auction-ready', vin: d.vin || null }));
    await self.registration.showNotification(d.title || 'Auction report ready', {
      body: d.body || '', tag: d.tag || ('auction-' + (d.vin || '')), renotify: true, data: { url, vin: d.vin || null },
      icon: 'icons/icon-192.png', badge: 'icons/favicon-32.png', vibrate: [120, 60, 120], timestamp: d.ts || Date.now() });
  })());
});
self.addEventListener('notificationclick', e => {
  e.notification.close();
  const target = new URL((e.notification.data && e.notification.data.url) || 'auction.html', self.registration.scope).href;
  e.waitUntil((async () => {
    const cs = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
    for (const c of cs) {
      if (new URL(c.url).pathname === new URL(target).pathname && 'focus' in c) { try { await c.navigate(target); } catch (err) {} return c.focus(); }
    }
    return self.clients.openWindow(target);
  })());
});
